CREATE VIEW WEATHER_HOURLY_3PM AS
SELECT 
    WEATHER_HOURLY.WEATHER_DATE,
       WEATHER_HOURLY.LOCATION_CODE,
       WEATHER_HOURLY.TIME,
       WIND_DIRECTION.WIND_DIRECTION AS WIND_DIR,
       WEATHER_HOURLY.WIND_SPEED,
       WEATHER_HOURLY.HUMIDITY,
       WEATHER_HOURLY.PRESSURE,
       WEATHER_HOURLY.CLOUD,
       WEATHER_HOURLY.TEMPERATURE
FROM WEATHER_HOURLY
JOIN WIND_DIRECTION ON WEATHER_HOURLY.WIND_DIR = WIND_DIRECTION.WIND_DIRECTION
WHERE TIME = 15
;

CREATE VIEW WEATHER_HOURLY_9AM AS
SELECT
    WEATHER_HOURLY.WEATHER_DATE,
       WEATHER_HOURLY.LOCATION_CODE,
       WEATHER_HOURLY.TIME,
       WIND_DIRECTION.WIND_DIRECTION AS WIND_DIR,
       WEATHER_HOURLY.WIND_SPEED,
       WEATHER_HOURLY.HUMIDITY,
       WEATHER_HOURLY.PRESSURE,
       WEATHER_HOURLY.CLOUD,
       WEATHER_HOURLY.TEMPERATURE
FROM WEATHER_HOURLY
JOIN WIND_DIRECTION ON WEATHER_HOURLY.WIND_DIR = WIND_DIRECTION.WIND_DIRECTION
WHERE TIME = 9
;

CREATE VIEW weather_details AS
SELECT LOCATIONS.LOCATION_NAME,
       WEATHER_DAILY.WEATHER_DATE,
       UU.MINTEMP,
       UU.MAXTEMP,
       WEATHER_DAILY.RAINFALL,
       WEATHER_DAILY.EVAPORATION,
       WEATHER_DAILY.SUNSHINE,
       WH9AM.WIND_DIR AS wind_dir_9am,
       WH3PM.WIND_DIR AS wind_dir_3pm,
       WH9AM.WIND_SPEED AS wind_speed_9am,
       WH3PM.WIND_SPEED AS wind_speed_3am,
       WH9AM.HUMIDITY AS humidity_9am,
       WH3PM.HUMIDITY AS humidity_3pm,
       WH9AM.PRESSURE AS pressure_9am,
       WH3PM.PRESSURE AS pressure_3pm,
       WH9AM.CLOUD AS cloud_9am,
       WH3PM.CLOUD AS cloud_3pm,
       WH9AM.TEMPERATURE AS temp_9am,
       WH3PM.TEMPERATURE AS temp_3pm,
       CASE WHEN WEATHER_DAILY.RAINFALL > 0 THEN 'Yes' ELSE 'No' END AS raintoday
FROM WEATHER_DAILY
JOIN LOCATIONS ON LOCATIONS.LOCATION_NAME = WEATHER_DAILY.location_code
JOIN (
    SELECT
           WEATHER_DAILY.LOCATION_CODE,
           WEATHER_DAILY.WEATHER_DATE,
           MIN(WEATHER_HOURLY.TEMPERATURE) AS MINTEMP,
           MAX(WEATHER_HOURLY.TEMPERATURE) AS MAXTEMP
    FROM WEATHER_DAILY
    JOIN WEATHER_HOURLY ON
            WEATHER_DAILY.LOCATION_CODE = WEATHER_HOURLY.LOCATION_CODE AND
            WEATHER_DAILY.WEATHER_DATE = WEATHER_HOURLY.WEATHER_DATE
    GROUP BY WEATHER_DAILY.LOCATION_CODE, WEATHER_DAILY.WEATHER_DATE
    ) uu ON uu.LOCATION_CODE = WEATHER_DAILY.LOCATION_CODE AND uu.WEATHER_DATE = WEATHER_DAILY.WEATHER_DATE
JOIN WEATHER_HOURLY_9AM WH9AM ON WH9AM.LOCATION_CODE = WEATHER_DAILY.LOCATION_CODE AND WH9AM.WEATHER_DATE = WEATHER_DAILY.WEATHER_DATE
JOIN WEATHER_HOURLY_3PM WH3PM ON WH3PM.LOCATION_CODE = WEATHER_DAILY.LOCATION_CODE AND WH3PM.WEATHER_DATE = WEATHER_DAILY.WEATHER_DATE
;
